config/routes.rb
Key1::Application.routes.draw do
  resources :keys

  resources :for_selects

  root 'keys#index'

end

app/models/for_select.rb
class ForSelect < ActiveRecord::Base
	# Create a 2d array to be used in "grouped_options_for_select" in "select-tag"
	# "db_model" is the name of the model containing all the select information
	# "code" is the value in the code field in the db_model that identifies
		# which group of values will appear in the grouped select
	# "grouped_options" is my gem which generates the 2d array
		# gem 'grouped_options', git: 'git@github.com:marcmentis/grouped_options.git'
	def self.GroupedSelect(facility, code, db_model)
		@forSelect = db_model.all
					  .where(facility: facility)
                      .where(code: code)
                      .order(option_order: :asc)  
	    # @grouped_options = ForSelect.grouped_options(@forSelect)
	    @grouped_options = GroupedOptions.grouped_options(@forSelect)
		
	end

	def self.CollectionForSelect(facility, code, db_model)
		select_collection = db_model.where(facility: facility)
									.where(code: code)
									.order(option_order: :asc)
	end
end

app/models/key.rb
class Key < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/for_selects_controller.rb
class ForSelectsController < ApplicationController
  before_action :set_for_select, only: [:show, :edit, :update, :destroy]

  # GET /for_selects
  # GET /for_selects.json
  def index
    @q = ForSelect.search(params[:q])
    @for_selects = @q.result.page(params[:page]).per(5)

    @totNumber = ForSelect.all.count
    @searchNumber = @q.result.count
  end

  # GET /for_selects/1
  # GET /for_selects/1.json
  def show
  end

  # GET /for_selects/new
  def new
    @for_select = ForSelect.new
    @grouped_options = ForSelect.GroupedSelect('9999', 'key', ForSelect)
  end

  # GET /for_selects/1/edit
  def edit
    @grouped_options = ForSelect.GroupedSelect('9999', 'key', ForSelect)
  end

  # POST /for_selects
  # POST /for_selects.json
  def create
    @for_select = ForSelect.new(for_select_params)

    respond_to do |format|
      if @for_select.save
        format.html { redirect_to @for_select, notice: 'For select was successfully created.' }
        format.json { render action: 'show', status: :created, location: @for_select }
      else
        format.html { render action: 'new' }
        format.json { render json: @for_select.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /for_selects/1
  # PATCH/PUT /for_selects/1.json
  def update
    respond_to do |format|
      if @for_select.update(for_select_params)
        format.html { redirect_to @for_select, notice: 'For select was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @for_select.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /for_selects/1
  # DELETE /for_selects/1.json
  def destroy
    @for_select.destroy
    respond_to do |format|
      format.html { redirect_to for_selects_url }
      format.js {}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_for_select
      @for_select = ForSelect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def for_select_params
      params.require(:for_select).permit(:code, :value, :text, :grouper, :option_order, :facility)
    end
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  before_action :set_key, only: [:show, :edit, :update, :destroy]

  # GET /keys
  # GET /keys.json
  def index
    @keys = Key.all
  end

  # GET /keys/1
  # GET /keys/1.json
  def show
  end

  # GET /keys/new
  def new
    @key = Key.new
  end

  # GET /keys/1/edit
  def edit
  end

  # POST /keys
  # POST /keys.json
  def create
    @key = Key.new(key_params)

    respond_to do |format|
      if @key.save
        format.html { redirect_to @key, notice: 'Key was successfully created.' }
        format.json { render action: 'show', status: :created, location: @key }
      else
        format.html { render action: 'new' }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keys/1
  # PATCH/PUT /keys/1.json
  def update
    respond_to do |format|
      if @key.update(key_params)
        format.html { redirect_to @key, notice: 'Key was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keys/1
  # DELETE /keys/1.json
  def destroy
    @key.destroy
    respond_to do |format|
      format.html { redirect_to keys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_key
      @key = Key.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def key_params
      params.require(:key).permit(:company, :description, :number, :checkout, :checkin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/for_selects_helper.rb
module ForSelectsHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/views/for_selects/_form.html.erb
<%= form_for(@for_select) do |f| %>
  <% if @for_select.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@for_select.errors.count, "error") %> prohibited this for_select from being saved:</h2>

      <ul>
      <% @for_select.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="large-3 columns panel radius">
    <div class="panel callout radius">
      <div class="field">
        <%= f.label :code %><br>
        <%= f.text_field :code %>
      </div>
      <div class="field">
        <%= f.label :value %><br>
        <%= f.text_field :value %>
      </div>
      <div class="field">
        <%= f.label :text %><br>
        <%= f.text_field :text %>
      </div>
      <div class="field">
        <%= f.label :grouper %><br>
        <%= f.text_field :grouper %>
      </div>
      <div class="field">
        <%= f.label :option_order %><br>
        <%= f.number_field :option_order %>
      </div>
      <div class="field">
        <%= f.label :facility %><br>
        <%= f.text_field :facility %>
        <%= select_tag(:sFor_select_facility, grouped_options_for_select(@grouped_options), prompt: 'Choose Facility') %>
      </div>
      <div class="actions">
        <%= f.submit class: "button tiny radius" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/for_selects/edit.html.erb
<h1>Editing for_select</h1>

<%= render 'form' %>

<%= link_to 'Show', @for_select %> |
<%= link_to 'Back', for_selects_path %>

app/views/for_selects/index.html.erb
<div class="row">
  <div class="large-5 columns large-offset-3 ">
      <h3>Listing for_selects</h3>
  </div>

</div>
<div class="row">
  <div class="large-9 columns">
    <div class="panel radius">
      <div class="panel callout radius">
        <%= search_form_for @q, id: 'fFor_select_filter' do |f| %>
        <div class="row collapse">
          <div class="hide">
            <div class="small-2 columns">
              <%= f.submit class: 'button tiny radius' %>
            </div>
          </div>
          <div class="small-12 columns">
            <div class="row collapse">
              <div class="small-1 columns">
                <%= f.label(:code_start, 'Code:', class: "right inline") %>
              </div>
              <div class="small-2 columns end">
                <%= f.search_field :code_start %>
              </div>

              <div class="small-2 columns">
                <%= f.label(:facility_eq, 'Facility:', class: "right inline") %>
              </div>
              <div class="small-2 left columns">
                <%= f.search_field :facility_eq %>
              </div> 

              <div class="small-2 columns">
                <%= f.label(:value_start, 'Value:', class: "right inline") %>
              </div>
              <div class="small-2 left columns">
                <%= f.search_field :value_start %>
              </div>   
            </div> 

            <div class="row collapse">
              <div class="small-1 columns">
                <%= f.label(:text_start, 'Text:', class: "right inline") %>
              </div>
              <div class="small-2 left columns">
                <%= f.search_field :text_start %>
              </div> 
              <div class="small-2 columns">
                <%= f.label(:grouper_start, 'Grouper:', class: "right inline") %>
              </div>
              <div class="small-2 left columns">
                <%= f.search_field :grouper_start %>
              </div> 

              <div class="small-2 columns">
                <%= f.label(:option_order_eq, 'Order:', class: "right inline") %>
              </div>
              <div class="small-2 left columns">
                <%= f.search_field :option_order_eq %>
              </div> 
            </div>           
          </div>
        </div>         
        <% end %>
      </div>

      <div class="row">
        <div class="small-12 small-offset-1 columns ">
          <table>
            <thead>
              <tr class="tableHeader">
                <th><%= sort_link(@q, :code, "Code") %></th>
                <th><%= sort_link(@q, :value, "Value") %></th>
                <th><%= sort_link(@q, :text, "Text") %></th>
                <th><%= sort_link(@q, :grouper, "Grouper") %></th>
                <th><%= sort_link(@q, :option_order, "Order") %></th>
                <th><%= sort_link(@q, :facility, "Facility") %></th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @for_selects.each do |for_select| %>
                <tr>
                  <td><%= for_select.code %></td>
                  <td><%= for_select.value %></td>
                  <td><%= for_select.text %></td>
                  <td><%= for_select.grouper %></td>
                  <td><%= for_select.option_order %></td>
                  <td><%= for_select.facility %></td>
                  <td><%= link_to 'Show', for_select %></td>
                  <td><%= link_to 'Edit', edit_for_select_path(for_select) %></td>
                  <td><%= link_to 'Destroy', for_select, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
                </tr>
              <% end %>
              <tr>
                <td colspan="5" class="tableFooter">
                  <%= paginate @for_selects %>
                </td>
                <td colspan="4" class="tableFooter">
                  <%= @searchNumber %> from <%= @totNumber %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
      </div>


    </div>
    
  </div>
</div>


<br>

<%= link_to 'New For select', new_for_select_path, class: "button tiny radius" %>

app/views/for_selects/new.html.erb
<h1>New for_select</h1>

<%= render 'form' %>

<%= link_to 'Back', for_selects_path %>

app/views/for_selects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @for_select.code %>
</p>

<p>
  <strong>Value:</strong>
  <%= @for_select.value %>
</p>

<p>
  <strong>Text:</strong>
  <%= @for_select.text %>
</p>

<p>
  <strong>Grouper:</strong>
  <%= @for_select.grouper %>
</p>

<p>
  <strong>Option order:</strong>
  <%= @for_select.option_order %>
</p>

<p>
  <strong>Facility:</strong>
  <%= @for_select.facility %>
</p>

<%= link_to 'Edit', edit_for_select_path(@for_select) %> |
<%= link_to 'Back', for_selects_path %>

app/views/keys/_form.html.erb
<%= form_for(@key) do |f| %>
  <% if @key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key.errors.count, "error") %> prohibited this key from being saved:</h2>

      <ul>
      <% @key.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :checkout %><br>
    <%= f.date_select :checkout %>
  </div>
  <div class="field">
    <%= f.label :checkin %><br>
    <%= f.date_select :checkin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keys/edit.html.erb
<h1>Editing key</h1>

<%= render 'form' %>

<%= link_to 'Show', @key %> |
<%= link_to 'Back', keys_path %>

app/views/keys/index.html.erb
<h1>Listing keys</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Description</th>
      <th>Number</th>
      <th>Checkout</th>
      <th>Checkin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @keys.each do |key| %>
      <tr>
        <td><%= key.company %></td>
        <td><%= key.description %></td>
        <td><%= key.number %></td>
        <td><%= key.checkout %></td>
        <td><%= key.checkin %></td>
        <td><%= link_to 'Show', key %></td>
        <td><%= link_to 'Edit', edit_key_path(key) %></td>
        <td><%= link_to 'Destroy', key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Key', new_key_path %>

app/views/keys/new.html.erb
<h1>New key</h1>

<%= render 'form' %>

<%= link_to 'Back', keys_path %>

app/views/keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @key.company %>
</p>

<p>
  <strong>Description:</strong>
  <%= @key.description %>
</p>

<p>
  <strong>Number:</strong>
  <%= @key.number %>
</p>

<p>
  <strong>Checkout:</strong>
  <%= @key.checkout %>
</p>

<p>
  <strong>Checkin:</strong>
  <%= @key.checkin %>
</p>

<%= link_to 'Edit', edit_key_path(@key) %> |
<%= link_to 'Back', keys_path %>

app/views/layouts/_header.html.erb
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><a href="#"><%= image_tag 'rails.jpg', size: '30x38' %> 
                        Key 1</a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li class="has-dropdown">
          <a href="#">Rt Item 1</a>
          <ul class="dropdown">
            <li><a href="#">Drop 1</a></li>
            <li><a href="#">Drop 2</a></li>
            <li class="has-dropdown">
              <a href="#">Nested Drop</a>
              <ul class="dropdown">
                <li><a href="#">Nested 1</a></li>
                <li><a href="#">Nested 2</a></li>
                <li><a href="#">Nested 3</a></li>
              </ul>
            </li>
            <li><a href="#">Drop 3</a></li>
          </ul>
        </li>
        <li><a href="#">Rt Item 2</a></li>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li><%= link_to("For Select", for_selects_path) %></li>
        <li><%= link_to("Keys", keys_path) %></li>
        
      </ul>
    </section>
  </nav>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Key1 Application" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div id="divContainer" class="row">
    <div class="large-12 columns">
      <%= render "layouts/header" %>

      <%= yield %>
      <%= javascript_include_tag "application" %>
    </div>
  </div>
  </body>
</html>